"""empty message

Revision ID: 4c4c90a2419a
Revises: 6a110faca246
Create Date: 2020-04-02 15:23:46.987741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c4c90a2419a'
down_revision = '6a110faca246'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Show',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['Artist.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['Venue.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'Venue', sa.Column('seeking_description', sa.String(length=200), nullable=True))
    op.add_column(u'Venue', sa.Column('seeking_talent', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'Venue', 'seeking_talent')
    op.drop_column(u'Venue', 'seeking_description')
    op.drop_table('Show')
    # ### end Alembic commands ###
