"""empty message

Revision ID: 76158bd3f363
Revises: 0e00edcb8dbc
Create Date: 2020-04-03 01:28:34.279594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76158bd3f363'
down_revision = '0e00edcb8dbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('artist', 'website', new_column_name ='website_link')
    op.alter_column('venue', 'website', new_column_name ='website_link')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('website', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_column('venue', 'website_link')
    op.add_column('artist', sa.Column('website', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_column('artist', 'website_link')
    # ### end Alembic commands ###
